"""PPT Animation Skill Package."""
from .core import (
    animate_pptx,
    animate_existing_ppt,
    get_animation_preview,
    get_animations_from_ppt,
    replicate_animations,
    create_background,
    add_textbox,
    add_card,
    add_line,
    TRANS_MAP,
    EFFECT_MAP,
    EFFECT_APPEAR,
    EFFECT_CHECKERBOARD,
    EFFECT_CIRCLE,
    EFFECT_BOX,
    COLOR_SCHEMES,
    DEFAULT_SCHEME,
    get_color_scheme_names,
    get_color_scheme,
    apply_scheme,
)

__version__ = "2.0.0"
__all__ = [
    "animate_pptx",
    "animate_existing_ppt",
    "get_animation_preview",
    "get_animations_from_ppt",
    "replicate_animations",
    "create_background",
    "add_textbox",
    "add_card",
    "add_line",
    "TRANS_MAP",
    "EFFECT_MAP",
    "EFFECT_APPEAR",
    "EFFECT_CHECKERBOARD",
    "EFFECT_CIRCLE",
    "EFFECT_BOX",
    "COLOR_SCHEMES",
    "DEFAULT_SCHEME",
    "get_color_scheme_names",
    "get_color_scheme",
    "apply_scheme",
]
